open-craft/xblock-poll

- poll/poll.py
- poll/public/css/poll.css
- poll/public/handlebars/poll_results.handlebars
Fix for width issue reported in MCKIN-3599 on the results screen: If a poll contains no images, the results are not as wide as they should be.
**Before**:
**After**:
> Fix: Results view is too narrow when no images are present

- poll/public/css/poll.css
- poll/public/css/themes/lms.css
- poll/public/handlebars/survey_results.handlebars
- poll/public/html/survey.html
- tests/integration/studio_scenarios.py
- tests/integration/test_defaults.py
Using th for question cells will ensure that screen reader users will have the questions announced to them as the move from row to row.
*None*
- [SOL-1995](https://openedx.atlassian.net/browse/SOL-1995)
- [LMS](http://dndv2-pr96.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/survey/): a predeployed instance of the XBlock.
- 18d5f78 *(updated 2016-08-15)*
1. Go to the [pre-deployed instance](http://dndv2-pr96.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/survey/) on the LMS, and log in as `staff@example.com`.
2. Using Firebug or similar, examine the question containers and check that they are using `<th>` elements, as opposed to `<td>` (see screenshot below).
3. With the Orca screen reader, test that when using the right keyboard shortcuts and …
> [SOL-1995] Ensure implicit row header cells use th elements

- poll/poll.py
- poll/public/html/survey.html
- setup.py
- tests/integration/test_functions.py
This PR improves a11y for survey blocks by linking radio buttons representing individual options with both questions and answers. That way, screen reader users can be certain that a given radio button is tied to a specific question and answer -- both questions and answers are announced to them as they move between options in the survey table.
cf. [SOL-2035](https://openedx.atlassian.net/browse/SOL-2035)
**Sandbox**
* LMS: http://xblock-poll-pr15.opencraft.hosting/
* Studio: http://studio-xblock-poll-pr15.opencraft.hosting/
Latest commit: https://github.com/open-craft/xblock-poll/pull/15/commits/d4388af5c1c8bee3b0c3d2519729b16ca614bc43
**Note**: Changes from #13 and #14 are present on the sandbox as well.
**Test instructions**
1. Add `"survey"` to advanced modules in Studio.
2. Add a …
> Associate survey options with corresponding question and answer

- poll/poll.py
- poll/public/handlebars/poll_results.handlebars
- poll/public/handlebars/poll_studio.handlebars
- poll/public/handlebars/survey_results.handlebars
- poll/public/html/poll.html
- poll/public/html/survey.html
- poll/public/js/poll.js
- poll/public/js/poll_edit.js
- setup.py
- tests/integration/test_functions.py
This PR contains several minor accessibility fixes for problems described in [SOL-2059]( https://openedx.atlassian.net/browse/SOL-2059):
>
- The screenreader text that accompanies each radio button is unnecessary. The aria-labelledby completely takes care of the accessible name for the control. (Adds unnecessary verbosity for screen reader users who hear the SR text as well as the label, which are identical).
- There is a `<script>` element that has an ID attribute on it (`"survey-results-template"`) that gets repeated if there are more than two polls on a page. I doubt an ID attribute is needed on a `<script>` elements, but since this is being used as some sort of template, perhaps there's something I'm missing. (Causes automated test failures since all IDs must be unique).
- When the …
> A11y fixes

- poll/public/html/poll.html
- poll/public/html/survey.html
- setup.py
Hi folks! This PR introduces a small markup change fixing some invalid HTML in the poll template. The associated JIRA is [AC-711](https://openedx.atlassian.net/browse/AC-711).
Currently, the input radio button `id` attributes start with a numeric `block_id`, which is [illegal in CSS](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier) as well as [HTML4](https://www.w3.org/TR/html401/types.html#type-name). While not technically illegal in HTML5, it still throws a DOM Exception 12 when queried with `querySelector`. We ran into this problem while running an accessibility audit with [edx/pa11ycrawler](https://github.com/edx/pa11ycrawler). To get around this, I prefixed the `id` attribute with the string `poll-`.
Aside from tests passing, is there anything else I need to do to get …
> [template] avoid potential invalid id attribute

- poll/public/html/survey.html
- setup.py
- tests/integration/test_functions.py
This PR makes two small accessibility changes to the survey template based on feedback from our SSB BART accessibility audit. They are as follows:
- Include the question text (or image alt text if present) in the description of the survey radio buttons, per https://openedx.atlassian.net/browse/TNL-6359
- Add `scope="row"` to the `<th>` elements in the survey table, per https://openedx.atlassian.net/browse/TNL-6360
@bradenmacdonald or @e-kolpakov, would you please review or assign a reviewer?
@cptvitamin, would you mind reviewing as well? I'll link a sandbox once it finishes building.
Thanks all!
> survey a11y improvements

- poll/public/js/poll.js
- setup.py
- tests/integration/test_submit_button.py
- tests/integration/xml/poll_submit_button.xml
**Summary:**  If submit button is clicked multiple times, multiple ajax requests are sent. To avoid this, we disable the submit button as soon as the submit button is clicked and enable it again at the end of the ajax call depending on the response from backend. This commit addresses EDUCATOR-273 issued in
openedx JIRA.
**Before:** ![before gif](https://raw.githubusercontent.com/ravi-ojha/ravi-ojha.github.io/master/assets/educator_273.gif)
See that? It creates noise in error log because of multiple ajax calls resulting in 500.
**After:** ![after gif](https://raw.githubusercontent.com/ravi-ojha/ravi-ojha.github.io/master/assets/educator_273_fix.gif)
Voila! Just one request.
> Disable submit button on button click to avoid multiple ajax calls

- poll/poll.py
- tests/integration/test_private_results.py
This enables mobile view. Over time we will work to improve the responsiveness of each webview version.
**Testing**:
1. Add Survey and Poll blocks to your course.
1. Publish the unit.
1. Without this patch: verify that the course blocks API reports `"student_view_multi_device": false` for both blocks.
1. With this patch: verify that the course blocks API reports `"student_view_multi_device": true` for both blocks.
Example of the course blocks API url is:
http://lms.mcka.local/api/courses/v1/blocks/?course_id=my/course/key&all_blocks=true&depth=all&requested_fields=student_view_multi_device&block_types_filter=poll,survey
**NOTE 1**: Course block API responses are cached, so you may see stale responses. One simple way to clear and rebuild the cache is to publish a random unit in your …
> Enable webview for Poll & Survey blocks

- poll/public/css/poll.css
- poll/public/js/poll.js
Hides element outline after poll is submitted; fixes JS bug where focus may be given to another poll block on the same page
**JIRA tickets**: [OC-2980](https://tasks.opencraft.com/browse/OC-2980) [MCKIN-5301](https://edx-wiki.atlassian.net/browse/MCKIN-5301)
**Discussions**: @bradenmacdonald identified an additional bug where the the selector to find the element to apply focus to was too broad.
**Dependencies**: None
**Merge deadline**: ASAP
**Testing instructions**:
1. Set up a unit with a poll xblock 
* Submit an answer
* See that no outline surrounds the block's HTML
**Reviewers**
> Hide element outline after poll is submitted

- poll/poll.py
Given the responsiveness improvements that have been added lately and the need to use the mobile webview, we are now ready to permanently mark this as mobile friendly.
Previously introduced into a branch via #29 but never merged to `master`.
> Mark Poll and Survey XBlocks as Mobile friendly

- poll/public/html/poll.html
- poll/public/html/poll_edit.html
- poll/public/html/survey.html
- setup.py
Hi I'm a developer on the Stanford team that runs a few OpenEdX instances and we are using this xblock in Vietnamese. I noticed the HTML strings weren't tagged for translation, so I've gone ahead and done it. I didn't touch the .po files since it's not clear from documentation how its done (custom handlebars strings, are these manually stitched together into the final text.po? Or some fiddling with config.yml and i18n_tools?)
@e-kolpakov @bradenmacdonald 
Not sure if I tagged the right people, apologies in advance.
> Tag HTML strings for translation

- poll/poll.py
- poll/public/css/poll.css
- poll/public/html/poll.html
- poll/public/html/survey.html
- poll/public/js/poll.js
- poll/tasks.py
- tests/unit/test_xblock_poll.py
Adds CSV export + download buttons to the Survey and Poll XBlocks.
**JIRA tickets**: [OC-2981](https://tasks.opencraft.com/browse/OC-2981) [MCKIN-5433](https://edx-wiki.atlassian.net/browse/MCKIN-5433)
**Testing instructions**:
1. In a course with a survey or poll xblock,
1. Click on the export button to queue a CSV export
1. Click the now-active download button to download the CSV
1. Notice the difference in formatting between survey and poll output
Screenshot:
**Reviewers**
> CSV export for LMS

- poll/poll.py
Fix the warning described in [TE-2583](https://openedx.atlassian.net/browse/TE-2583):
```
WARNING 7632 [py.warnings] fields.py:455 - /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/poll/poll.py:607: FailingEnforceTypeWarning: The value (('Y', 'Yes'), ('N', 'No'), ('M', 'Maybe')) could not be enforced (TypeError: Value stored in a List must be None or a list, found <type 'tuple'>)
scope=Scope.settings, help=_("Answer choices for this Survey")
```
As far as I can tell, this change shouldn't have any effect beyond satisfying code in the `xblock` package that the correct type of value was provided.
> Fix FailingEnforceTypeWarning in SurveyBlock

- poll/poll.py
- setup.py
- Change default value from tuple to list.
- Bump version to 1.5.1.
Fixes this warning message, which happens on every server restart:
```
2018-06-06 09:00:32,220 WARNING 2477 [py.warnings] fields.py:455
- /edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/poll/poll.py:607: 
FailingEnforceTypeWarning: The value (('Y', 'Yes'), 
('N', 'No'), ('M', 'Maybe')) could not be enforced 
(TypeError: Value stored in a List must be None or a list, found <type 'tuple'>)
scope=Scope.settings, help=_("Answer choices for this Survey")
```
> Fix frequent warning.

- setup.py
version bump to [1dc36a8](https://github.com/open-craft/xblock-poll/commit/1dc36a827a32fb651e8de97a9e539e70ce84b38f) (update translations)
> version bump to 1dc36a8 (update translations)

- poll/public/js/poll.js
- setup.py
Jira ticket: https://edx-wiki.atlassian.net/browse/MCKIN-8799
When downloading polling data, I follow the steps below:
1. Click view results
2. Click export data
3. Once the data is ready for download, download
4. The exported CSV of data is always the data from the last pull, not from today's date.
5. I refresh the page, follow steps 1 - 3, and then it downloads the most recent data. So I am following the process twice to ensure that this is the most accurate, up-to-date data.
> MCKIN-8799 Download button enabled only when final download url is ready

- poll/poll.py
- setup.py
- tests/unit/test_xblock_poll.py
This branch makes survey report generation more robust, protecting against the case where the stored user state for a survey response has no `choices` key.
* In Studio, [enable the Survey XBlock](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/exercises_tools/survey.html#survey-tool).
* Add a Survey block to a course and publish the course.
* Login as a student.
* Respond to the survey.
* In Studio, edit the survey, remove the question and add a new one, then publish the course.
* As the student, revisit the survey.
* As an admin user, navigate to Courses > Your Course > Responses.
* Select your survey and click Download Responses.
* In the LMS console, you will see an error:
```2019-02-28 18:04:17,162 WARNING 25065 [edx.celery.task] tasks_base.py:94 - …
```
> [BB-993] Fix a bug in report generation where a survey response has no choices key

- poll/poll.py
- setup.py
The poll xblock has custom completion but was publishing a progress event instead of a completion event, which is no longer supported. 
This PR updates the block to use the new completion API instead. 
**Testing instructions**:
1. Set up a could with the poll xblock. 
2. Make sure completion is enabled. 
3. Respond to a poll. 
4. Check if the poll has been marked as complete using the UI or by checking for a correstponding BlockCompletion entry (``from completion.models import BlockCompletion``), checking ``BlockCompletion.objects.last()`` should work.
5. The completion will not be reported. 
6. Install the version of the XBlock from this PR, and restart the LMS.
7. Respond to another poll. 
8. Check the completion entries again, you should see a completion entry for the block.
> [MCKIN-10391] Fix issues updating completion

- poll/poll.py
- poll/public/html/survey.html
- setup.py
- tests/integration/test_functions.py
- tests/integration/xml/survey_multiple.xml
This branch ensures that the HTML ID of radio buttons in surveys is unique across surveys. This avoids the problem of duplicate HTML IDs when more than one survey is present in a single unit whose answer keys happen to overlap.
* Install this branch in your devstack
* In Studio, create a unit with two sample surveys - keep the default questions and answers - and publish it.
* In the LMS browse to the survey.
* Using the browser's developer tools (or show source), verify that each of the radio buttons in the two surveys has a unique HTML ID.
> Ensure survey radio button ID uniqueness across surveys

- .travis.yml
- Makefile
It seems that since the previous PR (https://github.com/open-craft/xblock-poll/pull/60), the default distribution used by Travis CI has been changed from trusty to xenial, whcih causes the [old approach](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-directly) of using xvfb to fail. This PR updated the OS in use to Xenial and uses the [newer approach](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services).
> Fix travis config

- poll/tasks.py
- setup.py
The following celery task is not being executed:
* poll.tasks.export_csv_data
```
The message has been ignored and discarded.
Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.
The full contents of the message body was:
{u'utc': True, u'chord': None, u'args': [u'block-v1:HKPolyUx+HTM540x+2T2019a+type@survey+block@9da49dd09d954b5e9057cd520d032992', u'course-v1:HKPolyUx+HTM540x+2T2019a'], u'retries': 0, u'expires': None, u'task': u'poll.tasks.export_csv_data', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'037df1ad-a8f8-40c2-a5ae-f3f8534aef46'} (387b)
Traceback (most recent call last):
File …
```
> Fix Unregistered Celery Task Error

- poll/poll.py
This code path doesn't get hit during the test suite because it depends on the existence of code from edx-platform, so it was missed during the Python 3 upgrade.  Just updated this response to match the others so it doesn't blow up with `TypeError: You cannot set the body to a text value without a charset` in production.
> Add missing charset to response

- poll/poll.py
- setup.py
Jira tikcet: https://edx-wiki.atlassian.net/browse/MCKIN-12693
If a choice is updated/added in polls after a user has submitted a response for the old choice, this code crashes since the id for the new choice has changed.
The code crash occurs while generating polls/survey responses.
> MCKIN-12693 Handle updated choice ids in polls

- poll/poll.py
- setup.py
[PROD-1295](https://openedx.atlassian.net/browse/PROD-1295)
Issue:
People were unable to download poll reports due to conflict in StudentModule 
Fix: 
Updated StudentModule path and there was another issue with the concatenation of the list which seems likely was caused due to python update.
> Fixed StudentModule conflicting path 

- poll/poll.py
- setup.py
Fixed the most frequently occurring deprecation warnings.
```
Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release
``` 
- most of these were due to a single mis-configured resource path with a leading slash.
```
xblock.fragment is deprecated. Please use web_fragments.fragment instead
```
FYI -- @jmbowman, @xitij2000
> Fix most frequent deprecation warnings

- poll/poll.py
- setup.py
```
The correct import is
`common.djangoapps.static_replace`.
Support for the deprecated import path will be removed soon.
Bump version to 1.10.2
```
See [this forum post for context](https://discuss.openedx.org/t/koa-will-change-how-edx-platform-code-is-imported/3610).
This is related to the [the impending removal of support for deprecated edx-platform import paths](https://github.com/edx/edx-platform/pull/25932).
> Fix deprecated edx-platform import of static_replace

- poll/public/js/poll.js
If the "Export to CSV" button fails to launch a task, it currently doesn't display the error message properly. Instead, an error message can only be seen in the browser console, which just says `error is undefined`.
This fixes the code so that the actual error message will be displayed:
See https://openedx.atlassian.net/browse/TNL-8370 and https://github.com/edx/edx-platform/pull/28019 for more information about this issue.
> Fix error message display when CSV export fails [MNG-2273]

- poll/__init__.py
- poll/public/js/poll_edit.js
- Move the `preventDefault` function before the conditional in `poll-move-up` and `poll-move-down` click events.
- This change is to avoid opening a new tab page when clicking the Move up/Move down buttons when the Poll block is in an Iframe
- Related bug: [Testing report of Advanced block editors](https://docs.google.com/document/d/1-noO87_eIzc1A4FHNiO9kdlU30t60OaYHqVBxg9tfHo/edit?tab=t.0#heading=h.9gff493zcqs1)
- Internal ticket: [FAL-4041](https://tasks.opencraft.com/browse/FAL-4041)
- Checkout this branch locally
- Add it to the tutor mount list using `tutor mounts add ./xblock-poll`
- Rebuild images using `tutor images build openedx-dev`
- Go to a Course
- Go to `Settings > Advanced Settings` on the header menu
- Make sure you have `poll` and `survey` on the "Advanced Module List"
- …
> refactor: Move preventDefault in move up and move down events [FC-0076]

- poll/__init__.py
- poll/public/js/poll_edit.js
Select the correct container when removing an answer.
Fixes: https://github.com/openedx/wg-build-test-release/issues/455
When deleting an answer, the hint text was not being removed
##After
Deleting an answer correctly deletes the whole container.
https://github.com/user-attachments/assets/2697baa1-7f1e-422c-8565-8680eb5cf919
> fix: delete answers now remove the entire container

- poll/__init__.py
- poll/public/css/poll_edit.css
- poll/public/html/poll_edit.html
- poll/public/js/poll_edit.js
Received feedback on this issue: https://github.com/openedx/wg-build-test-release/issues/454
When there is an error on the fields of a poll, there is no feedback to the user, so they don't know they hace to fix something. 
The validation and error handling is being done on the backend, so in order to make validations on the frontend and point exactly to the input with the issue we would have to move/replicate all the validation logic on the frontend, which I'm not sure we want to do.
My proposal to avoid that re-work and still let the user know that there are issue they have to fix, is to add an `Error section` that will be hidden at first, and if there are any issues that came from the backend, we can list them there.
Please look at the following video. …
> fix: show errors when inputs are incorrect
